import "bootstrap/dist/css/bootstrap.min.css";
import '../styles/globals.css'
import Head from 'next/head'
import MainContainer from '../componentes/mainContainer'
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {
  return (
    <div>
      <MainContainer>
        <Head>
          <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <Component {...pageProps} />
      </MainContainer>
    </div>
  );
}

/* 
<html lang="en">
      <body>{children}</body>
    </html>
    <div>
*/
