import "bootstrap/dist/css/bootstrap.min.css";
import '../styles/globals.css'
import Head from 'next/head'
import MainContainer from '../componentes/mainContainer'
import React, {useState, useEffect} from "react";
import {login, onAuthChanged, registrar} from '../utils/firebase/authService'
import styles from '../styles/myApp.module.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {

  const [user, setUser] = useState(null)
  const [isLogin, setLogin] = useState(true)

  const handlerLogin = async () => {
    const valueEmail = document.getElementById('username').value
    const valuePass = document.getElementById('password').value

    if(valueEmail && valuePass){
      console.log(valueEmail)
      console.log(valuePass)

      login(valueEmail, valuePass).then((user) => {
        console.log(user)
      }).catch((error) => {
        console.log(error.code)
        if (error.code == 'auth/invalid-credential') {
          console.log('As credênciais fornecidas são inválidas. Cadastre-se!')
          //openNotification({placement: 'topRight', title: 'ERRO', descricao: 'SENHA INVÁLIDA. TENTE NOVAMENTE!'})
        }
      })
    }
  }

  useEffect(() => {
    function navHome(){
      return onAuthChanged((user) => {
        if(user){
          setUser(user)
        }
        else{
          setUser(user)
        }
      })
    }
    return navHome()
  },[])

  const toggleOpLogin = () => {
    setLogin(!isLogin)
  }

  const handlerRegistrar = async () => {
    const valueEmail = document.getElementById('username').value
    const valuePass = document.getElementById('password').value

    if(valueEmail && valuePass){
      console.log(valueEmail)
      console.log(valuePass)

      registrar(valueEmail, valuePass).then((user) => console.log(user)).catch((error) => {
        if (error.code == 'auth/email-already-in-use') {
          console.log('ESTE E-MAIL JÁ ESTA SENDO USADO. TENTE OUTRO!')
          //openNotification({placement: 'topRight', title: 'ERRO', descricao: 'ESTE E-MAIL JÁ ESTA SENDO USADO. TENTE OUTRO!'})
        } else if (error.code == 'auth/invalid-email'){
          console.log('ESTE É UM E-MAIL INVÁLIDO. TENTE NOVAMENTE!')
          //openNotification({placement: 'topRight', title: 'ERRO', descricao: 'ESTE É UM E-MAIL INVÁLIDO. TENTE NOVAMENTE!'})
        } else if(error.code == 'auth/weak-password'){
          console.log('SENHA FRACA. UTILIZE AO MENOS 6 CARACTERES!')
          //openNotification({placement: 'topRight', title: 'ERRO', descricao: 'SENHA FRACA. UTILIZE AO MENOS 6 CARACTERES!'})
        }
      })
    }
  }

  if(user){
    return (
      <div>
        <MainContainer>
          <Head>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
          </Head>
          <Component {...pageProps} />
        </MainContainer>
      </div>
    );
  }

  return(
    <div className={styles.body}>
      <main className={styles.main}>
          <div className={styles.title}>{isLogin ? 'Bem Vindo' : 'Crie Sua conta'}</div>
          <div class='form-floating'>
            <input 
                type="text" 
                id="username" 
                class="form-control shadow-none" 
                required
                placeholder="fulado123@gmail.com" 
                minlength="1" 
                maxlength="50"
            >
            </input>
            <label for="username">Usuário</label>
          </div>
          <div style={{ height: '10px'}}></div>
          <div class='form-floating'>
            <input 
                type="password" 
                id="password" 
                class="form-control shadow-none" 
                required
                placeholder="********" 
                minlength="1" 
                maxlength="8"
            >
            </input>
            <label for="password">Senha</label>
          </div>
          <div className={styles.button01} onClick={isLogin ? handlerLogin : handlerRegistrar}>{isLogin ? 'Login' : 'Cadastrar'}</div>
          <div className={styles.button02} onClick={toggleOpLogin}>{isLogin ? 'Ainda não tem Conta? Cadastre-se agora' : 'Voltar ao Login'}</div>
      </main>
    </div>
  )
  
}

/* 
<html lang="en">
      <body>{children}</body>
    </html>
    <div>
*/
