// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-hWS8n5A_TQ3zbViFLwh3-eORIPlx0E',
    appId: '1:484432276309:web:4a7cc69133964cdbdf9ddc',
    messagingSenderId: '484432276309',
    projectId: 'delivery-app-12b3e',
    authDomain: 'delivery-app-12b3e.firebaseapp.com',
    storageBucket: 'delivery-app-12b3e.appspot.com',
    measurementId: 'G-JPPZBJ7XR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudhjbfo-Pz-plpXxsXaGVaM8_5aPnixM',
    appId: '1:484432276309:android:8a0e75f3af2e429cdf9ddc',
    messagingSenderId: '484432276309',
    projectId: 'delivery-app-12b3e',
    storageBucket: 'delivery-app-12b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xi_gsynSQbD_RX9qloPvoWQOpVNKAZk',
    appId: '1:484432276309:ios:3d18ad7f103e7f46df9ddc',
    messagingSenderId: '484432276309',
    projectId: 'delivery-app-12b3e',
    storageBucket: 'delivery-app-12b3e.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xi_gsynSQbD_RX9qloPvoWQOpVNKAZk',
    appId: '1:484432276309:ios:3d18ad7f103e7f46df9ddc',
    messagingSenderId: '484432276309',
    projectId: 'delivery-app-12b3e',
    storageBucket: 'delivery-app-12b3e.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-hWS8n5A_TQ3zbViFLwh3-eORIPlx0E',
    appId: '1:484432276309:web:23a2b438678d13fadf9ddc',
    messagingSenderId: '484432276309',
    projectId: 'delivery-app-12b3e',
    authDomain: 'delivery-app-12b3e.firebaseapp.com',
    storageBucket: 'delivery-app-12b3e.appspot.com',
    measurementId: 'G-3FTLFJGYPF',
  );
}
